wiki/web/forms.py
"""
    Forms
    ~~~~~
"""
from flask_wtf import FlaskForm as Form
from wtforms import BooleanField
from wtforms import StringField as TextField
from wtforms import TextAreaField
from wtforms import PasswordField
from wtforms.validators import InputRequired
from wtforms.validators import ValidationError

from wiki.core import clean_url
from wiki.web import current_wiki
from wiki.web import current_users


class URLForm(Form):
    url = TextField('', [InputRequired()])

    def validate_url(form, field):
        if current_wiki.exists(field.data):
            raise ValidationError('The URL "%s" exists already.' % field.data)

    def clean_url(self, url):
        return clean_url(url)


class SearchForm(Form):
    term = TextField('', [InputRequired()])
    ignore_case = BooleanField(
        description='Ignore Case',
        # FIXME: default is not correctly populated
        default=True)


class EditorForm(Form):
    title = TextField('', [InputRequired()])
    body = TextAreaField('', [InputRequired()])
    tags = TextField('')


class LoginForm(Form):
    name = TextField('', [InputRequired()])
    password = PasswordField('', [InputRequired()])

    def validate_name(form, field):
        user = current_users.get_user(field.data)
        if not user:
            raise ValidationError('This username does not exist.')

    def validate_password(form, field):
        user = current_users.get_user(form.name.data)
        if not user:
            return
        if not user.check_password(field.data):
            raise ValidationError('Username and password do not match.')

wiki/web/__init__.py
import os
from flask import current_app
from flask import Flask
from flask import g
from flask_login import LoginManager
from werkzeug.local import LocalProxy

from wiki.core import Wiki
from wiki.web.user import UserManager

class WikiError(Exception):
    pass

def get_wiki():
    wiki = getattr(g, '_wiki', None)
    if wiki is None:
        wiki = g._wiki = Wiki(current_app.config['CONTENT_DIR'])
    return wiki

current_wiki = LocalProxy(get_wiki)

def get_users():
    users = getattr(g, '_users', None)
    if users is None:
        users = g._users = UserManager(current_app.config['USER_DIR'])
    return users

current_users = LocalProxy(get_users)


def create_app(directory):
    app = Flask(__name__)
    app.config['CONTENT_DIR'] = directory
    app.config['TITLE'] = u'wiki'
    try:
        app.config.from_pyfile(
            os.path.join(app.config.get('CONTENT_DIR'), 'config.py')
        )
    except IOError:
        msg = "You need to place a config.py in your content directory."
        raise WikiError(msg)

    loginmanager.init_app(app)

    from wiki.web.routes import bp
    app.register_blueprint(bp)

    return app


loginmanager = LoginManager()
loginmanager.login_view = 'wiki.user_login'

@loginmanager.user_loader
def load_user(name):
    return current_users.get_user(name)

wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect


bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		 <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
		 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
		 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='theme.css') }}">
		 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='code-css/friendly.css') }}">
	</head>

	<body>
		<nav class="navbar navbar-expand-md navbar-light bg-light">
		  <a class="navbar-brand" href="#">Wiki</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		      <li class="nav-item ">
		        <a class="nav-link" href="{{ url_for('wiki.home') }}">Главная <span class="sr-only">(current)</span></a>
		      </li>
					<li class="nav-item ">
						<a class="nav-link" href="{{ url_for('wiki.index') }}">Статьи <span class="sr-only">(current)</span></a>
					</li>
		      <li class="nav-item ">
		         <a class="nav-link" href="{{ url_for('wiki.tags') }}">Теги <span class="sr-only">(current)</span></a>
		      </li>
					<li class="nav-item ">
						 <a class="nav-link" href="{{ url_for('wiki.create') }}">Новая страница <span class="sr-only">(current)</span></a>
					</li>
		      <li class="nav-item ">
		         <a class="nav-link" href="{{ url_for('wiki.search') }}">Поиск<span class="sr-only">(current)</span></a>
		      </li>
		    </ul>
				<ul class="nav justify-content-end">
					{% if current_user.is_anonymous %}
					<li class="nav-item">
						 <a class="nav-link" href="{{ url_for('wiki.user_login') }}">Авторизоваться <span class="sr-only">(current)</span></a>
					</li>
					{% else %}
					<li class="nav-item">
						 <a class="nav-link" href="{{ url_for('wiki.user_logout') }}">Выйти<span class="sr-only">(current)</span></a>
					</li>
					{% endif %}
				</ul>
		  </div>
		</nav>


		<main  role="main" class="container-fluent">
			<div class="row">
				<div class="col-12  text-center w-100 p-4">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="col-lg-1">
				</div>
				<div class="col-10 col-lg-8 fixed">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Произошли ошибки при проверке ввода. Пожалуйста, отметьте выбранные поля ниже.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="col-2">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</main>
  		 <footer class="footer">
     		 <div class="container-fluent">
      		  <p class="text-center text-muted">   Copyright © 2018  All rights reserved. </p>
     		 </div>
   		 </footer>

	       <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
           <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
           <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

		   <script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		   </script>
	</body>
</html>

wiki/web/templates/base_wide.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		 <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
		 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
		 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='theme.css') }}">
		 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='code-css/monokai.css') }}">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="#">Wiki</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
		      <li class="nav-item ">
		        <a class="nav-link" href="{{ url_for('wiki.home') }}">Главная <span class="sr-only">(current)</span></a>
		      </li>
					<li class="nav-item ">
						<a class="nav-link" href="{{ url_for('wiki.index') }}">Статьи <span class="sr-only">(current)</span></a>
					</li>
		      <li class="nav-item ">
		         <a class="nav-link" href="{{ url_for('wiki.tags') }}">Теги <span class="sr-only">(current)</span></a>
		      </li>
					<li class="nav-item ">
						 <a class="nav-link" href="{{ url_for('wiki.create') }}">Новая страница <span class="sr-only">(current)</span></a>
					</li>
		      <li class="nav-item ">
		         <a class="nav-link" href="{{ url_for('wiki.search') }}">Поиск<span class="sr-only">(current)</span></a>
		      </li>
		    </ul>
				<ul class="nav justify-content-end">
					{% if current_user.is_anonymous %}
					<li class="nav-item">
						 <a class="nav-link" href="{{ url_for('wiki.user_login') }}">Авторизоваться <span class="sr-only">(current)</span></a>
					</li>
					{% else %}
					<li class="nav-item">
						 <a class="nav-link" href="{{ url_for('wiki.user_logout') }}">Выйти<span class="sr-only">(current)</span></a>
					</li>
					{% endif %}
				</ul>
		  </div>
		</nav>


		<div class="container">
			<div class="row">
				<div class="col-12  text-center w-100 p-4">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Произошли ошибки при проверке ввода. Пожалуйста, отметьте выбранные поля ниже.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
			</div>
		</div>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Создать новую страницу{% endblock title %}
{% block content %}

<div class="card bg-light" style="width: 30 em;">
  <div class="card-body">
		<form method="POST" class="form-inline offset1" >
			{{ form.hidden_tag() }}
			{{ input(form.url, placeholder="URL новой страницы", autocomplete="off") }}
			<input type="submit" class="btn btn-success btn-sm" value="Создать">
		</form>
  </div>
</div>


{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Благодарим вас за создание нового контента!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% extends "base_wide.html" %}

{% block title -%}
Wiki Редактор
{%- endblock title %}



{% block content %}

<ul class="nav nav-tabs" id="MyTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active"  id="editor-tab" data-toggle="tab" href="#editor" role="tab" aria-controls="editor" aria-selected="true">Редактор</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="preview-tab" data-toggle="tab" href="#preview" role="tab" aria-controls="preview" aria-selected="false">Предпросмотр</a>
  </li>
</ul>
<div class="tab-content" id="MyTabContent">
<div  class="tab-pane fade show active" id="editor" role="tabpanel" aria-labelledby="editor-tab">
  <form method="post" class="form">
    {{ form.hidden_tag() }}
    {{ input(form.title, placeholder="Заголовок", class="col-12", autocomplete="off") }}
    {{ input(form.body, placeholder="Markdown", class="col-12", rows="20") }}
    {{ input(form.tags, placeholder="Тег (разделяем запятой)", class="col-12", autocomplete="off") }}

    <div class="form-actions w-100 p-2">

        <div class="float-left" >
        <a class="btn btn-outline-success my-2 my-sm-0 " href="#preview" id="previewbtn">Предпросмотр</a>
        </div>
        <div class="pull-right btn-group float-right" role="group"  aria-label="Basic example">
        <a class="btn btn-outline-success my-2 my-sm-0" href="{{ url_for('wiki.display', url=page.url) }}">Отменить</a>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Сохранить</button>
        </div>
      </div>
    </form>
  </div>
<div class="tab-pane fade" id="preview"></div>
</div>
</div>



{% endblock content %}


{% block postscripts -%}
{{ super() }}
$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Загрузка...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('С предварительным просмотром возникла проблема.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Добро пожаловать в новую вики!
{% endblock title %}

{% block content %}
<p>Вы еще не создали ни одной статьи. Ваша вики рекомендует, сделать это сейчас, так как любой пользователь увидит эту страницу в первую очередь, вы же хотите произвести хорошее впечатление, не так ли?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Создать домашнюю страницу</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Все статьи{% endblock title %}

{% block content %}
{% if pages %}
  <table class="table table-bordered table-striped table-hover table-sm"">
	  <thead   class="thead-light">
			<tr>
				<th class="text-center">#</th>
				<th class="text-center">Заглавие</th>
				<th class="text-center">URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td class="text-center" >{{ loop.index }}</td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>Еще нет страниц.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<div class="btn-group-vertical">

<a class="btn btn-outline-success my-2 my-sm-0" href="{{ url_for('wiki.create') }}">Новая страница</a>
<a class="btn btn-outline-success my-2 my-sm-0"href="{{ url_for('wiki.tags') }}">Список тегов</a>
<a class="btn btn-outline-success my-2 my-sm-0" href="{{ url_for('wiki.search') }}">Искать</a>

</div>
{% endblock sidebar %}

wiki/web/templates/login.html
{% extends "base_wide.html" %}

{% block title %}Авторизация{% endblock title %}

{% block content %}
<form class="form-signin" method="POST">
	<h1 class="h5 mb-3 font-weight-normal text-center">Пожалуйста, войдите</h1>
	<div class="col-md-4 mx-auto">
	{{ form.hidden_tag() }}
	<div class="form-label-group">
	   {{ form.name(placeholder='Логин', class="form-control") }}
	</div>
	<div class="form-label-group">
	  {{ form.password(placeholder='Пароль', class="form-control", type="password"  ) }}
	</div>
	<button class="btn btn-md btn-primary btn-block" type="submit" value="Login">Войти</button>
</div>
</form>

{% endblock content %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Будьте осторожны, старый URL-адрес станет недействительным!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
	{{ page.title }}
{% endblock title %}

{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <h3>Вы уверены?</h3>
    </div>
    <div class="modal-body">
      <p>Вы уверены что хотите удалить {{ page.title }}?  Это не может быть отменено.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Нет</a>
      <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Да, удалить.</a>
    </div>
  </div>
	{{ page }}
{% endblock content %}

{% block sidebar %}

		<div class="btn-group-vertical mb-3 d-flex justify-content-center">
		  <a  class="btn btn-outline-success " href="{{ url_for('wiki.edit', url=page.url) }}">Изменить</a>
	  	<a  class="btn btn-outline-success " href="{{ url_for('wiki.move', url=page.url) }}">Перенести</a>
	  	<a  class="btn btn-outline-success " href="#confirmDelete" data-toggle="modal" class="text-error">Удалить</a>
		</div>

{% if page.tags %}
  <ul class="list-group">
    <li class="list-group-item list-group-item-action flex-column align-items-start active text-center"><h6>Теги</h4></li>

      {% for tag in page.tags.split(',') %}
        <li class="list-group-item list-group-item-action flex-column align-items-start text-center"><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}


{% endblock sidebar %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Результаты для "{{ search }}"
{% else %}
	 Поиск
{% endif %}
{% endblock title %}

{% block content %}
<div class="card bg-light" style="width: 30 em;">
  <div class="card-body">
    <div class="row">
	   <div class="col-10 offset1">
		  <form class="form-inline well" method="POST">
			  {{ form.hidden_tag() }}
			  {{ form.term(placeholder='Поиск.. (принято регулярное выражение)', autocomplete="off", class= "col-7") }}
            {{ form.ignore_case( class="form-check-input  mx-1" ) }} <span >Ignore Case</span>
			  <input type="submit" class="btn btn-outline-success mx-1 my-sm-0" value="Искать!">
		  </form>
  	</div>
  </div>
</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>Нет результатов для вашего поиска.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Тег страницы : {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}


	<table class="table table-bordered table-striped table-hover table-sm">
		<thead   class="thead-light">
			<tr>
				<th class="text-center">#</th>
				<th class="text-center">Заглавие</th>
				<th class="text-center">URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td class="text-center" >{{ loop.index }}</td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>Нет страниц с тегами {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Тегированные страницы{% endblock title %}

{% block content %}
{% if tags %}
<table class="table table-bordered table-striped table-hover table-sm">
	<thead   class="thead-light">
			<tr>
				<th class="text-center">#</th>
				<th class="text-center">Тег</th>
				<th class="text-center">Количество статей</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td class="text-center" >{{ loop.index }}</td>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>Пока нет тегов.</p>
{% endif %}
{% endblock content %}